<?php
	/*
		Call flow command ok:
		"<param><value><string>1</string></value></param>
      <param><value><string>admin</string></value></param>
      <param><value><string>pleasure</string></value></param>
      <param><value><struct><member><name>title</name><value>a</value></member><member><name>description</name><value>aaa</	value></member></struct></value></param>
		<param><value><boolean>true</boolean></value></param>"
		2006年11月22日 
		Gm good Luck!
	*/
	include("inc/lib/xmlrpc.inc");
	include("inc/lib/xmlrpcs.inc");
	include("inc/lib/xmlrpc_wrappers.inc");
	include("inc/ghome.lib.php");

	class xmlrpc_server_methods_container
	{
		/*
		* Method used to test logging of php warnings generated by user functions.
		*/
		function phpwarninggenerator($m)
		{
			$a = $b; // this triggers a warning in E_ALL mode, since $b is undefined
			return new xmlrpcresp(new xmlrpcval(1, 'boolean'));
		}
	}

	$addTwo_sig=array(array($xmlrpcInt,$xmlrpcInt,$xmlrpcInt));
        $addTwo_doc='Calucate the sum of tow Integer,return Integer';
	
	function addTwo($m){
		$a=$m->getParam(0);
		$b=$m->getParam(1);
		$c=$a->scalarval()+$b->scalarval();
		return new xmlrpcresp(new xmlrpcval($c,"int"));
	}

	$InsertPos_sig=array(array($xmlrpcString,$xmlrpcString,$xmlrpcString,$xmlrpcString,$xmlrpcStruct,$xmlrpcBoolean));
	$InsertPos_doc='insert a post form xmlrpc';
	function InsertPost($m){
		$id=gaCount();
		$id++;
		$log_isShow=1;
		$Cate_ID=1;
		$log_Weather=1;
		$log_From='del.icio.us';
		$log_Url='http://gm8pleasure.vip.533.net';
		$blog_id=$m->getParam(0);
		$blog_id=$blog_id->scalarval();
		$author=$m->getParam(1);
		$author=$author->scalarval();
		$password=$m->getParam(2);
		$password=$password->scalarval();
		if($author!='admin' || $password!=getAdminPass())
			$auth_err=1;
		if($auth_err){
			$auth_err_msg='Authorize error!';
			return new xmlrpcresp(0, $xmlrpcerruser+1, $auth_err_msg);
		}

		$blog_Data=$m->getParam(3);
		$temp=$blog_Data->structmem('title');
		$log_Title=$temp->scalarval();
		$temp=$blog_Data->structmem('description');
		$log_Intro=$temp->scalarval();

		$hasMore=0;
		$log_details=$log_Intro;
		$day=getGTime();		
		$str_Write=$id."\t".$day."\t".$Cate_ID."\t".$log_Title."\t".$log_IsShow."\t".$log_Weather."\t".$log_From."\t".$log_FromURL."\t".$log_Intro."\t".$hasMore."\t".$log_details."\n";
                $fHandle=fopen("data/$id.cgi",'w');
		fwrite($fHandle,$str_Write);
		fclose($fHandle);

		$countFile='data/arcount.cgi';
		$fcount=fopen($countFile,'w');
		fwrite($fcount,$id);
		fclose($fcount);

		return new xmlrpcresp(new xmlrpcval(strval($id), "string"));
	}
	$o=new xmlrpc_server_methods_container;
	$a=array(
	  "metaWeblog.newPost" => array(
	    "function" => "InsertPost",
	    "signature" => $InsertPos_sig,
	    "docstring" => $InsertPos_doc
  		   ),
		"examples.addTwo" => array(
          "function" => "addTwo",
	     "signature" => $addTwo_sig,
	     "docstring" => $addTwo_doc			
		)
  	);
	$s=new xmlrpc_server($a, false);
	$s->setdebug(3);
	/* $s->compress_response = true;*/

	$s->service();
?>
