<?php
	/*
		Call flow command ok:

		<param><value><int>1</int></value></param>
		<param><value><string>pleasure8</string></value></param>
		<param><value><string>blizzard</string></value></param>
		<param><value>
		<struct>
		<member><name>title</name><value><string>a</string></value></member>
		<member><name>description</name>
		<value><string>aaa</string></value>
		</member>
		<member><name>categories</name>
		<value>
		<array>
		<data>
		<value>
		<string>del.icio.us</string>
		</value>
		</data>
		</array>
		</value>
		</member>
		</struct>
		</value>
		</param>
		<param><value><int>1</int></value></param>

		2006-11-22日 
		Gm good Luck!
	*/
	include("inc/lib/xmlrpc.inc");
	include("inc/lib/xmlrpcs.inc");

	class xmlrpc_server_methods_container
	{
		/*
		* Method used to test logging of php warnings generated by user functions.
		*/
		function phpwarninggenerator($m)
		{
			$a = $b; // this triggers a warning in E_ALL mode, since $b is undefined
			return new xmlrpcresp(new xmlrpcval(1, 'boolean'));
		}
	}

	$InsertPos_sig=array(array($xmlrpcString,$xmlrpcInt,$xmlrpcString,$xmlrpcString,$xmlrpcStruct,$xmlrpcInt));
	$InsertPos_doc='insert a post form xmlrpc';
	function InsertPost($m){
		$author=$m->getParam(1);
		$password=$m->getParam(2);				
		$blog_id=$m->getParam(0);
			
		$blog_Data=$m->getParam(3);
		$blog_Title=$blog_Data->structmem('title');
		$blog_Desc=$blog_Data->structmem('description');
		$blog_Cats=$blog_Data->structmem('categories');
		$blog_Data=new xmlrpcval(array(
			'title'=>$blog_Title,
			'description'=>$blog_Desc,
			'categories'=>$blog_Cats),
			"struct"
		);

		$url='https://storage.msn.com/storageservice/MetaWeblog.rpc';
		$published=$m->getParam(4);
		$client=new xmlrpc_client($url);
		$f=new xmlrpcmsg('metaWeblog.newPost');
		$blog_id='MyBlog';
		$blog_id=new xmlrpcval($blog_id,'string');
		$publisehd=new xmlrpcval(true,'boolean');
		$f->addParam($blog_id);
		$f->addParam($author);
		$f->addParam($password);
		$f->addParam($blog_Data);
		$f->addParam($published);
		$rv=$client->send($f);
		$id='Success';
		if($rv->faultCode()){
			$id=$rv->faultString();
		}

		return new xmlrpcresp(new xmlrpcval($id, "string"));
	}

	$setPostCategory_sig=array(array($xmlrpcBoolean,$xmlrpcInt,$xmlrpcString,$xmlrpcString,$xmlrpcArray));
	$setPostCategory_doc='set a Blog to some Category';
	function setPostCategory($m){
		$author=$m->getParam(1);
		$author=$author->scalarval();
		$password=$m->getParam(2);
		$password=$password->scalarval();
			if(!login_ok($author,$password)){
			$auth_err_msg='Authorize error!';
			return new xmlrpcresp(0, $xmlrpcerruser+1, $auth_err_msg);
		}
		
		$blog_id=$m->getParam(0);
		$blog_id=$blog_id->scalarval();	

		return new xmlrpcresp(new xmlrpcval(true,"boolean"));
	}

	$o=new xmlrpc_server_methods_container;
		$a=array(
		  "metaWeblog.newPost" => array(
			"function" => "InsertPost",
			"signature" => $InsertPos_sig,
			"docstring" => $InsertPos_doc
			   ),		
		 "mt.setPostCategories" => array(
			 "function"=>"setPostCategory",
			 "signature"=>$setPostCategory_sig,
			 "docstring"=>$setPostCategory_doc
			)		 
		);
		$s=new xmlrpc_server($a, false);
		$s->setdebug(3);
		/* $s->compress_response = true;*/

		$s->service();
?>
