<?php	
	include("inc/head.php");
	include("inc/ghome.lib.php");
?>
<TABLE class="wordbreak" cellSpacing="6" cellPadding="4" width="768" align="center" background="images/blog_main.gif" border="0">
   <tr>
    <td>
	   <?php
			include("inc/admin_left.php");
	   ?>
	</td>
	<td>
	   <?php
	   ?>
	</td>
  </tr>
</table>
<?php
include("inc/footer.php");
?>
